import '@/styles/globals.css';
import { Metadata } from 'next';
import { Acme } from 'next/font/google';
import Header from '@/components/layout/Header';
const acme = Acme({ subsets: ['latin'], weight: ['400'] });

export const metadata: Metadata & { title: string; description: string } = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={acme.className}>
        <div className="main">
          <div className="gradient" />
        </div>
        <main className="app">
          <Header />
          {children}
        </main>
      </body>
    </html>
  );
}

export async function getServerSideProps(context: any) {
  console.log(context);
  return {
    props: {
      name: 'asd',
    },
  };
}
